### ISSUE TITLE
Issue_upload_resume - Uploading resume leads to a "No file found" error

### ISSUE THREAD

**Issue by prav29** [se2024-jpg/WolfTrack6.0#16]
Clicking on "Add Resume" leads to an error: FileNotFoundError: [Errno 2] No such file or directory:
<img width="1702" alt="Screenshot 2024-10-30 at 10 15 00 PM" src="https://github.com/user-attachments/assets/343f6c92-5095-44b5-b25f-5887c533347c">

**Comment by girish1430** [comment]
I think we need to look for any hardcoded paths, that could be causing this issue

**Comment by joeljogy** [comment]
Thanks for fixing the issue, @prav29. I'm not running into this error anymore now.
