### ISSUE TITLE
Issue_recommender - The redirect URL for the identified jobs doesn't work

### ISSUE THREAD

**Issue by prav29** [se2024-jpg/WolfTrack6.0#5]
The information for the web scraped jobs is shown on the job recommender page but the redirect URL doesn't work

**Comment by joeljogy** [comment]
Do you think we can leverage the redirect URL received from the Adzuna API for this?

**Comment by joeljogy** [comment]
Tested the functionality after merging the change to Feature branch. Looks good! Thanks, @prav29 for resolving the issue.
